title: "Stan for Psych and Neurosci"
description: A tongue-in-cheek practical introduction to applying Bayes for Psychologists and Neuroscientists, using Python and Stan
show_downloads: true
google_analytics:
theme: jekyll-theme-dinky
