title: "Bayes for Psychology and Neuroscience, with Python and Stan"
description: A tongue-in-cheek practical introduction to applying Bayes for Psychologists and Neuroscientists, using Python and Stan
show_downloads: true
google_analytics:
theme: jekyll-theme-dinky
