title: "Statistical Methods for Research Workers: Bayes for Psychology & Neuroscientists"
description: A tongue-in-cheek practical introduction to applying Bayes for Psychologists and Neuroscientists, using Python and Stan
show_downloads: true
google_analytics:
theme: jekyll-theme-dinky
